name: backport

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      is_prelease: true
    outputs:
      asdf: ${{ steps.ffff.outputs.asdf }}
    steps:
      - if: ${{ !env.is_prelease && env.is_prelease == true }}
        id: ffff
        run:
          echo "asdf=$asdf" >> $GITHUB_OUTPUT
