name: backport

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    outputs:
      asdf: ${{ steps.ffff.outputs.asdf }}
    steps:
      - id: ffff
        run:
          echo "asdf=$asdf" >> $GITHUB_OUTPUT
