name: backport

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      is_prelease: false
    outputs:
      asdf: ${{ steps.ffff.outputs.asdf }}
    steps:
      - id: ffff
        run:
          asdf=true
          echo "asdf=$asdf" >> $GITHUB_OUTPUT
      - if: ${{ env.is_prelease }}
        run:
          echo "test"
